### ISSUE TITLE
Lazy zipWithIndex

### ISSUE THREAD

**Issue by ryan-williams** [hammerlab/magic-rdds#3]
A `zipWithIndex` implementation that doesn't run a job immediately should be possible.

**Comment by sadikovi** [comment]
I tried doing this, it will still trigger job, but at least it does not do it when you call method, it will do it, when action is called or user asked for partitions. Will submit PR on this, it is essentially slight modification on Spark's `zipWithIndex`.

**Comment by ryan-williams** [comment]
Fixed by #9, thx @sadikovi !
